[package]
name = "spysheets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# gtk = { version = "0.4.8", package = "gtk4" }
serde_json = "1.0"
serde_yaml = "0.9.13"
csv = "1.1"